"""
pipeline/retrieval/models.py
============================
Pydantic models and schemas for Phase 5: Hybrid RAG + Retrieval.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class QueryType(str, Enum):
    GENERAL = "GENERAL"
    SECTION_LOOKUP = "SECTION_LOOKUP"
    DEFINITION = "DEFINITION"
    OBLIGATION = "OBLIGATION"
    RIGHT = "RIGHT"
    PENALTY = "PENALTY"
    PROCEDURE = "PROCEDURE"
    CONTRACT_CLAUSE = "CONTRACT_CLAUSE"
    JUDGMENT = "JUDGMENT"
    COMPARISON = "COMPARISON"
    CROSS_REFERENCE = "CROSS_REFERENCE"


class RetrievalStatus(str, Enum):
    FOUND = "FOUND"
    LOW_EVIDENCE = "LOW_EVIDENCE"
    NO_EVIDENCE = "NO_EVIDENCE"


class RetrievalFilters(BaseModel):
    """
    Optional metadata filters applied prior to or during candidate retrieval.
    """
    document_type: Optional[str] = None
    source_authority: Optional[str] = None
    legal_domain: Optional[str] = None
    document_id: Optional[str] = None
    version_id: Optional[str] = None
    version_group_id: Optional[str] = None
    synthetic: Optional[bool] = None
    chunk_type: Optional[str] = None
    date: Optional[str] = None
    tenant_id: Optional[str] = None


class Candidate(BaseModel):
    """
    Internal retrieval candidate generated by Lexical or Semantic search.
    """
    chunk_id: str
    kb_chunk_id: str
    document_id: str
    version_id: Optional[str] = None
    version_group_id: Optional[str] = None
    score: float = 0.0
    method: str = "semantic"  # "lexical" | "semantic"
    lexical_rank: Optional[int] = None
    semantic_rank: Optional[int] = None
    raw_lexical_score: Optional[float] = None
    raw_semantic_score: Optional[float] = None
    rerank_score: Optional[float] = None
    chunk_data: Dict[str, Any] = Field(default_factory=dict)


class RetrievedEvidence(BaseModel):
    """
    Provenance-rich evidence record returned by the retrieval pipeline (Section 28).
    """
    rank: int
    chunk_id: str
    kb_chunk_id: str

    document_id: str
    version_group_id: Optional[str] = None
    version_id: Optional[str] = None

    document_title: Optional[str] = None
    document_type: Optional[str] = None
    chunk_type: str = "SECTION"

    title: Optional[str] = None
    chapter: Optional[str] = None
    section: Optional[str] = None
    subsection: Optional[str] = None
    clause: Optional[str] = None

    text: str

    lexical_score: Optional[float] = None
    semantic_score: Optional[float] = None
    fusion_score: float = 0.0
    rerank_score: Optional[float] = None

    source_authority: str = "SYNTHETIC"
    synthetic: bool = True

    page_start: Optional[int] = None
    page_end: Optional[int] = None

    provenance_id: Optional[str] = None
    source_document_id: Optional[str] = None
    source_sha256: Optional[str] = None

    retrieval_methods: List[str] = Field(default_factory=list)

    @property
    def score(self) -> float:
        return self.rerank_score or self.fusion_score or 0.0


class SupportingContext(BaseModel):
    """
    Auxiliary legal context expanded from primary evidence (parents, definitions, cross-references).
    """
    parent_chunks: List[Dict[str, Any]] = Field(default_factory=list)
    definitions: List[Dict[str, Any]] = Field(default_factory=list)
    cross_references: List[Dict[str, Any]] = Field(default_factory=list)


class EvidenceBundle(BaseModel):
    """
    Final canonical evidence object produced by Phase 5 and consumed by Phase 6 (Section 31).
    """
    query: str
    normalized_query: str
    query_type: QueryType = QueryType.GENERAL
    retrieval_status: RetrievalStatus = RetrievalStatus.FOUND

    filters: Optional[RetrievalFilters] = None
    retrieval_config: Dict[str, Any] = Field(default_factory=dict)

    results: List[RetrievedEvidence] = Field(default_factory=list)
    supporting_context: SupportingContext = Field(default_factory=SupportingContext)

    retrieval_timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    embedding_model: str = "legal-dense-v1"
    retrieval_version: str = "1.0.0"

    debug_info: Optional[Dict[str, Any]] = None

    @property
    def primary_evidence(self) -> List[RetrievedEvidence]:
        return self.results


class RetrievalResponse(BaseModel):
    """
    Stable API response contract for Phase 5 (Section 67).
    """
    query: str
    normalized_query: str
    query_type: QueryType
    retrieval_status: RetrievalStatus
    filters: Optional[Dict[str, Any]] = None
    retrieval_config: Dict[str, Any]
    results: List[RetrievedEvidence]
    supporting_context: SupportingContext
    retrieval_metadata: Dict[str, Any]
