"""
pipeline/synthetic/contract_builder.py
======================================
Generates 30 synthetic commercial contracts across 10 categories with deliberate edge clauses.
Edge clauses enable evaluation of clause extraction, risk assessment, redlining, and contract comparison.
"""

from __future__ import annotations

from typing import Any, Dict, List, Tuple

from pipeline.core.metadata import DocumentType, LegalDomain, SourceAuthority, DocumentStatus
from pipeline.synthetic.taxonomy import SYNTHETIC_COMPANIES

CONTRACT_CATEGORIES = [
    ("MSA", "Master Services Agreement", LegalDomain.COMMERCIAL_CORPORATE.value),
    ("NDA", "Mutual Non-Disclosure Agreement", LegalDomain.CONTRACT_LAW.value),
    ("EMP", "Executive Employment Agreement", LegalDomain.EMPLOYMENT_LABOUR.value),
    ("LEASE", "Commercial Real Estate Lease", LegalDomain.PROPERTY_REAL_ESTATE.value),
    ("SAAS", "Enterprise Cloud Software License Agreement", LegalDomain.IT_CYBER_LAW.value),
    ("PROC", "Vendor Supply & Procurement Agreement", LegalDomain.COMMERCIAL_CORPORATE.value),
    ("CONS", "Independent Consulting Agreement", LegalDomain.CONTRACT_LAW.value),
    ("IP", "Intellectual Property Assignment Agreement", LegalDomain.INTELLECTUAL_PROPERTY.value),
    ("JV", "Joint Venture Collaboration Agreement", LegalDomain.COMMERCIAL_CORPORATE.value),
    ("SETTLE", "Commercial Settlement & Mutual Release Agreement", LegalDomain.ARBITRATION_ADR.value),
]

# Variations for contract comparison and edge clause detection
CONTRACT_CONFIGS = [
    # 1. MSAs (SYN-CONT-001 to 003)
    {
        "id": "SYN-CONT-001",
        "cat": "MSA",
        "title": "Master Services Agreement (Standard Enterprise)",
        "party_a": "Aarav Technologies Pvt. Ltd. (Synthetic)",
        "party_b": "Neelam Cloud Services India Ltd. (Synthetic)",
        "term_days": 30,
        "liability_cap": "Total fees paid in preceding 12 months",
        "indemnity": "Mutual IP and confidentiality indemnity",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Arbitration under Bharat Arbitration Rules in Dakshin Pradesh",
        "confidentiality_years": 3,
        "non_compete_months": 0,
        "audit_notice_days": 14,
    },
    {
        "id": "SYN-CONT-002",
        "cat": "MSA",
        "title": "Master Services Agreement (Aggressive Vendor Terms)",
        "party_a": "Bhoomi Infrastructure & Logistics LLP (Synthetic)",
        "party_b": "Veda Data Analytics Pvt. Ltd. (Synthetic)",
        "term_days": 90,
        "liability_cap": "Fixed amount of ₹50,00,000",
        "indemnity": "Unilateral customer indemnity for third party claims",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "Arbitration in Paschim Rashtra; Sole arbitrator appointed by Vendor",
        "confidentiality_years": 5,
        "non_compete_months": 12,
        "audit_notice_days": 30,
    },
    {
        "id": "SYN-CONT-003",
        "cat": "MSA",
        "title": "Master Services Agreement (Customer Favorable)",
        "party_a": "Chaitanya Consumer Goods Ltd. (Synthetic)",
        "party_b": "Pratham Software Solutions Pvt. Ltd. (Synthetic)",
        "term_days": 15,
        "liability_cap": "Uncapped liability for breach of data privacy and gross negligence",
        "indemnity": "Comprehensive vendor indemnity covering all regulatory fines",
        "governing_law": "Laws of Union of Bharat; Courts of Uttaraanchal",
        "dispute": "High Court of Uttaraanchal jurisdiction",
        "confidentiality_years": 7,
        "non_compete_months": 6,
        "audit_notice_days": 2,
    },
    # 2. NDAs (SYN-CONT-004 to 006)
    {
        "id": "SYN-CONT-004",
        "cat": "NDA",
        "title": "Mutual Non-Disclosure Agreement (Standard 3-Year)",
        "party_a": "Suraksha Cybersecurity Systems LLP (Synthetic)",
        "party_b": "Aarav Technologies Pvt. Ltd. (Synthetic)",
        "term_days": 30,
        "liability_cap": "Mutual direct damages capped at ₹1,00,00,000",
        "indemnity": "Standard breach defense",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Mediation followed by Arbitration",
        "confidentiality_years": 3,
        "non_compete_months": 0,
        "audit_notice_days": 7,
    },
    {
        "id": "SYN-CONT-005",
        "cat": "NDA",
        "title": "Unilateral Non-Disclosure Agreement (Perpetual Trade Secrets)",
        "party_a": "Kaveri Healthtech Innovations Pvt. Ltd. (Synthetic)",
        "party_b": "Samarth Engineering Consultants Pvt. Ltd. (Synthetic)",
        "term_days": 0, # No early termination
        "liability_cap": "Uncapped liability for trade secret disclosure",
        "indemnity": "Full indemnification including attorney fees",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "Exclusive jurisdiction of Commercial Court, Paschim Rashtra",
        "confidentiality_years": 99, # Perpetual
        "non_compete_months": 24,
        "audit_notice_days": 1,
    },
    {
        "id": "SYN-CONT-006",
        "cat": "NDA",
        "title": "Bilateral Technology Evaluation NDA",
        "party_a": "Daksha Renewable Energy Solutions Ltd. (Synthetic)",
        "party_b": "Zenith FinTech Services Pvt. Ltd. (Synthetic)",
        "term_days": 15,
        "liability_cap": "₹25,00,000",
        "indemnity": "Mutual hold harmless",
        "governing_law": "Laws of Union of Bharat; Courts of Purvanchal",
        "dispute": "Arbitration in Purvanchal",
        "confidentiality_years": 2,
        "non_compete_months": 0,
        "audit_notice_days": 5,
    },
    # 3. Employment Agreements (SYN-CONT-007 to 009)
    {
        "id": "SYN-CONT-007",
        "cat": "EMP",
        "title": "Chief Technology Officer Employment Agreement",
        "party_a": "Neelam Cloud Services India Ltd. (Synthetic)",
        "party_b": "Vikramaditya Sengupta (Executive) (Synthetic)",
        "term_days": 90,
        "liability_cap": "No employee liability except for willful criminal misconduct",
        "indemnity": "Company indemnifies Executive for official acts",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Arbitration in Dakshin Pradesh",
        "confidentiality_years": 5,
        "non_compete_months": 12,
        "audit_notice_days": 0,
    },
    {
        "id": "SYN-CONT-008",
        "cat": "EMP",
        "title": "Senior AI Research Scientist Employment Contract",
        "party_a": "Aarav Technologies Pvt. Ltd. (Synthetic)",
        "party_b": "Dr. Ananya Deshmukh (Scientist) (Synthetic)",
        "term_days": 60,
        "liability_cap": "3 months gross salary",
        "indemnity": "IP assignment with moral rights waiver",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "Labour Court & High Court of Paschim Rashtra",
        "confidentiality_years": 5,
        "non_compete_months": 24,
        "audit_notice_days": 0,
    },
    {
        "id": "SYN-CONT-009",
        "cat": "EMP",
        "title": "Regional Sales Director Employment Contract",
        "party_a": "Chaitanya Consumer Goods Ltd. (Synthetic)",
        "party_b": "Rajeshwar Rao (Director) (Synthetic)",
        "term_days": 30,
        "liability_cap": "1 month base salary",
        "indemnity": "Standard indemnity",
        "governing_law": "Laws of Union of Bharat; Courts of Uttaraanchal",
        "dispute": "District Court, Uttaraanchal",
        "confidentiality_years": 2,
        "non_compete_months": 6,
        "audit_notice_days": 0,
    },
    # 4. Commercial Lease Agreements (SYN-CONT-010 to 012)
    {
        "id": "SYN-CONT-010",
        "cat": "LEASE",
        "title": "Commercial Office Lease Agreement (Tech Park)",
        "party_a": "Bhoomi Infrastructure & Logistics LLP (Synthetic)",
        "party_b": "Neelam Cloud Services India Ltd. (Synthetic)",
        "term_days": 90,
        "liability_cap": "Security deposit amount (6 months rent)",
        "indemnity": "Tenant indemnifies Landlord against invitee injuries",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Civil Court of Dakshin Pradesh",
        "confidentiality_years": 1,
        "non_compete_months": 0,
        "audit_notice_days": 7,
    },
    {
        "id": "SYN-CONT-011",
        "cat": "LEASE",
        "title": "Industrial Warehouse Lease Deed",
        "party_a": "Bhoomi Infrastructure & Logistics LLP (Synthetic)",
        "party_b": "Pavan Logistics & Freight Corp. (Synthetic)",
        "term_days": 180,
        "liability_cap": "3 months rent forfeiture",
        "indemnity": "Environmental contamination strict indemnity by Tenant",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "Arbitration in Paschim Rashtra",
        "confidentiality_years": 1,
        "non_compete_months": 0,
        "audit_notice_days": 1,
    },
    {
        "id": "SYN-CONT-012",
        "cat": "LEASE",
        "title": "Retail Mall Anchor Store Lease Agreement",
        "party_a": "Vistara Retail Enterprises LLP (Synthetic)",
        "party_b": "Chaitanya Consumer Goods Ltd. (Synthetic)",
        "term_days": 60,
        "liability_cap": "₹1,50,00,000",
        "indemnity": "Mutual premises liability indemnity",
        "governing_law": "Laws of Union of Bharat; Courts of Purvanchal",
        "dispute": "Commercial Court, Purvanchal",
        "confidentiality_years": 2,
        "non_compete_months": 12, # Radius restriction
        "audit_notice_days": 14,
    },
    # 5. SaaS / Software Licensing (SYN-CONT-013 to 015)
    {
        "id": "SYN-CONT-013",
        "cat": "SAAS",
        "title": "Enterprise Cloud Infrastructure Subscription Agreement",
        "party_a": "Neelam Cloud Services India Ltd. (Synthetic)",
        "party_b": "Mitra Digital Payment Solutions Ltd. (Synthetic)",
        "term_days": 30,
        "liability_cap": "12 months subscription fees",
        "indemnity": "Vendor IP indemnity subject to timely notice",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Fast-track Arbitration in Dakshin Pradesh",
        "confidentiality_years": 3,
        "non_compete_months": 0,
        "audit_notice_days": 30,
    },
    {
        "id": "SYN-CONT-014",
        "cat": "SAAS",
        "title": "Cybersecurity Threat Analytics SaaS Master Agreement",
        "party_a": "Suraksha Cybersecurity Systems LLP (Synthetic)",
        "party_b": "Zenith FinTech Services Pvt. Ltd. (Synthetic)",
        "term_days": 60,
        "liability_cap": "2x annual contract value",
        "indemnity": "Full breach indemnity with ₹10 Crore super-cap",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "Arbitration in Paschim Rashtra",
        "confidentiality_years": 5,
        "non_compete_months": 0,
        "audit_notice_days": 7,
    },
    {
        "id": "SYN-CONT-015",
        "cat": "SAAS",
        "title": "Core Banking API Middleware License Agreement",
        "party_a": "Zenith FinTech Services Pvt. Ltd. (Synthetic)",
        "party_b": "Mitra Digital Payment Solutions Ltd. (Synthetic)",
        "term_days": 120,
        "liability_cap": "Fees paid in past 6 months",
        "indemnity": "Exclusive IP warranty",
        "governing_law": "Laws of Union of Bharat; Courts of Uttaraanchal",
        "dispute": "High Court of Uttaraanchal",
        "confidentiality_years": 5,
        "non_compete_months": 12,
        "audit_notice_days": 10,
    },
    # 6. Vendor Supply / Procurement (SYN-CONT-016 to 018)
    {
        "id": "SYN-CONT-016",
        "cat": "PROC",
        "title": "Solar Photovoltaic Module Supply Framework Contract",
        "party_a": "Daksha Renewable Energy Solutions Ltd. (Synthetic)",
        "party_b": "Samarth Engineering Consultants Pvt. Ltd. (Synthetic)",
        "term_days": 45,
        "liability_cap": "100% of order purchase value",
        "indemnity": "Warranty and product defect indemnity",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "Arbitration in Paschim Rashtra",
        "confidentiality_years": 3,
        "non_compete_months": 0,
        "audit_notice_days": 5,
    },
    {
        "id": "SYN-CONT-017",
        "cat": "PROC",
        "title": "Precision Diagnostic Equipment Procurement Agreement",
        "party_a": "Kaveri Healthtech Innovations Pvt. Ltd. (Synthetic)",
        "party_b": "Suraksha Cybersecurity Systems LLP (Synthetic)",
        "term_days": 30,
        "liability_cap": "Replacement of non-conforming goods or refund",
        "indemnity": "Regulatory non-compliance hold harmless",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Commercial Court, Dakshin Pradesh",
        "confidentiality_years": 3,
        "non_compete_months": 0,
        "audit_notice_days": 2,
    },
    {
        "id": "SYN-CONT-018",
        "cat": "PROC",
        "title": "Fleet EV Battery Pack Supply and Buyback Agreement",
        "party_a": "Pavan Logistics & Freight Corp. (Synthetic)",
        "party_b": "Daksha Renewable Energy Solutions Ltd. (Synthetic)",
        "term_days": 90,
        "liability_cap": "Total value of defective batch",
        "indemnity": "Battery thermal recall indemnity",
        "governing_law": "Laws of Union of Bharat; Courts of Purvanchal",
        "dispute": "Arbitration in Purvanchal",
        "confidentiality_years": 3,
        "non_compete_months": 0,
        "audit_notice_days": 14,
    },
    # 7. Independent Consultant Agreements (SYN-CONT-019 to 021)
    {
        "id": "SYN-CONT-019",
        "cat": "CONS",
        "title": "Strategic Cloud Architecture Consulting Agreement",
        "party_a": "Pratham Software Solutions Pvt. Ltd. (Synthetic)",
        "party_b": "Veda Data Analytics Pvt. Ltd. (Synthetic)",
        "term_days": 14,
        "liability_cap": "Total fees received under applicable statement of work",
        "indemnity": "Consultant indemnifies against gross negligence",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Mediation",
        "confidentiality_years": 2,
        "non_compete_months": 0,
        "audit_notice_days": 7,
    },
    {
        "id": "SYN-CONT-020",
        "cat": "CONS",
        "title": "Regulatory Environmental Compliance Advisory Contract",
        "party_a": "Samarth Engineering Consultants Pvt. Ltd. (Synthetic)",
        "party_b": "Bhoomi Infrastructure & Logistics LLP (Synthetic)",
        "term_days": 30,
        "liability_cap": "₹10,00,000",
        "indemnity": "No indemnity for third party administrative fines",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "Courts of Paschim Rashtra",
        "confidentiality_years": 3,
        "non_compete_months": 12,
        "audit_notice_days": 3,
    },
    {
        "id": "SYN-CONT-021",
        "cat": "CONS",
        "title": "FinTech Payment Risk Modeling Retainer Agreement",
        "party_a": "Mitra Digital Payment Solutions Ltd. (Synthetic)",
        "party_b": "Zenith FinTech Services Pvt. Ltd. (Synthetic)",
        "term_days": 30,
        "liability_cap": "6 months retainer fees",
        "indemnity": "Client holds consultant harmless",
        "governing_law": "Laws of Union of Bharat; Courts of Uttaraanchal",
        "dispute": "Arbitration in Uttaraanchal",
        "confidentiality_years": 4,
        "non_compete_months": 6,
        "audit_notice_days": 7,
    },
    # 8. IP Assignment Agreements (SYN-CONT-022 to 024)
    {
        "id": "SYN-CONT-022",
        "cat": "IP",
        "title": "Proprietary Machine Learning Algorithm Assignment Deed",
        "party_a": "Veda Data Analytics Pvt. Ltd. (Synthetic)",
        "party_b": "Aarav Technologies Pvt. Ltd. (Synthetic)",
        "term_days": 0, # Irrevocable
        "liability_cap": "Total consideration paid for assignment",
        "indemnity": "Assignor warrants sole ownership and non-infringement",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Exclusive High Court of Dakshin Pradesh",
        "confidentiality_years": 99,
        "non_compete_months": 36,
        "audit_notice_days": 0,
    },
    {
        "id": "SYN-CONT-023",
        "cat": "IP",
        "title": "Medical Diagnostic Device Patent Transfer Agreement",
        "party_a": "Kaveri Healthtech Innovations Pvt. Ltd. (Synthetic)",
        "party_b": "Suraksha Cybersecurity Systems LLP (Synthetic)",
        "term_days": 0,
        "liability_cap": "₹5,00,00,000",
        "indemnity": "Patent validity and infringement indemnity",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "Commercial Division, High Court of Paschim Rashtra",
        "confidentiality_years": 10,
        "non_compete_months": 24,
        "audit_notice_days": 0,
    },
    {
        "id": "SYN-CONT-024",
        "cat": "IP",
        "title": "Trademark and Brand Portfolio Assignment Deed",
        "party_a": "Chaitanya Consumer Goods Ltd. (Synthetic)",
        "party_b": "Vistara Retail Enterprises LLP (Synthetic)",
        "term_days": 0,
        "liability_cap": "Consideration amount of ₹2,50,00,000",
        "indemnity": "Full brand defense indemnity",
        "governing_law": "Laws of Union of Bharat; Courts of Purvanchal",
        "dispute": "Arbitration in Purvanchal",
        "confidentiality_years": 5,
        "non_compete_months": 18,
        "audit_notice_days": 0,
    },
    # 9. Joint Venture / Collaboration (SYN-CONT-025 to 027)
    {
        "id": "SYN-CONT-025",
        "cat": "JV",
        "title": "Green Hydrogen Grid Consortium Agreement",
        "party_a": "Daksha Renewable Energy Solutions Ltd. (Synthetic)",
        "party_b": "Bhoomi Infrastructure & Logistics LLP (Synthetic)",
        "term_days": 180,
        "liability_cap": "Proportional to equity contribution (50:50)",
        "indemnity": "Mutual cross-indemnification for operational defaults",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "International Chamber arbitration in Bharat",
        "confidentiality_years": 7,
        "non_compete_months": 24,
        "audit_notice_days": 15,
    },
    {
        "id": "SYN-CONT-026",
        "cat": "JV",
        "title": "Digital Health AI Screening Consortium Deed",
        "party_a": "Kaveri Healthtech Innovations Pvt. Ltd. (Synthetic)",
        "party_b": "Aarav Technologies Pvt. Ltd. (Synthetic)",
        "term_days": 90,
        "liability_cap": "Capital contribution of each party",
        "indemnity": "Clinical trial liability shared equally",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Arbitration in Dakshin Pradesh",
        "confidentiality_years": 5,
        "non_compete_months": 12,
        "audit_notice_days": 10,
    },
    {
        "id": "SYN-CONT-027",
        "cat": "JV",
        "title": "Last-Mile Autonomous Freight Pilot Partnership",
        "party_a": "Pavan Logistics & Freight Corp. (Synthetic)",
        "party_b": "Pratham Software Solutions Pvt. Ltd. (Synthetic)",
        "term_days": 60,
        "liability_cap": "₹1,00,00,000 per incident",
        "indemnity": "Traffic accident liability allocated to software operator",
        "governing_law": "Laws of Union of Bharat; Courts of Purvanchal",
        "dispute": "Tribunal of Purvanchal",
        "confidentiality_years": 3,
        "non_compete_months": 12,
        "audit_notice_days": 7,
    },
    # 10. Settlement / Release Agreements (SYN-CONT-028 to 030)
    {
        "id": "SYN-CONT-028",
        "cat": "SETTLE",
        "title": "Software Licensing Dispute Settlement Deed",
        "party_a": "Neelam Cloud Services India Ltd. (Synthetic)",
        "party_b": "Veda Data Analytics Pvt. Ltd. (Synthetic)",
        "term_days": 0, # Irrevocable upon payment
        "liability_cap": "Settlement payment sum of ₹75,00,000",
        "indemnity": "Comprehensive mutual release of all claims",
        "governing_law": "Laws of Union of Bharat; Courts of Paschim Rashtra",
        "dispute": "High Court of Paschim Rashtra",
        "confidentiality_years": 99,
        "non_compete_months": 0,
        "audit_notice_days": 0,
    },
    {
        "id": "SYN-CONT-029",
        "cat": "SETTLE",
        "title": "Supply Chain Quality Dispute Release and Waiver",
        "party_a": "Chaitanya Consumer Goods Ltd. (Synthetic)",
        "party_b": "Samarth Engineering Consultants Pvt. Ltd. (Synthetic)",
        "term_days": 0,
        "liability_cap": "Settlement refund sum of ₹32,00,000",
        "indemnity": "Waiver of all past and future claims arising from batch defects",
        "governing_law": "Laws of Union of Bharat; Courts of Uttaraanchal",
        "dispute": "Courts of Uttaraanchal",
        "confidentiality_years": 5,
        "non_compete_months": 0,
        "audit_notice_days": 0,
    },
    {
        "id": "SYN-CONT-030",
        "cat": "SETTLE",
        "title": "Commercial Real Estate Lease Termination Settlement",
        "party_a": "Bhoomi Infrastructure & Logistics LLP (Synthetic)",
        "party_b": "Vistara Retail Enterprises LLP (Synthetic)",
        "term_days": 0,
        "liability_cap": "Retention of security deposit ₹40,00,000",
        "indemnity": "Full mutual release upon peaceful vacant possession",
        "governing_law": "Laws of Union of Bharat; Courts of Dakshin Pradesh",
        "dispute": "Courts of Dakshin Pradesh",
        "confidentiality_years": 3,
        "non_compete_months": 0,
        "audit_notice_days": 0,
    },
]

def generate_synthetic_contracts() -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]]]:
    """
    Generates 30 synthetic contracts with deliberate edge clauses.
    Returns:
        (documents, sections, structured_contracts)
    """
    documents: List[Dict[str, Any]] = []
    all_sections: List[Dict[str, Any]] = []
    structured_contracts: List[Dict[str, Any]] = []

    for cfg in CONTRACT_CONFIGS:
        doc_id = cfg["id"]
        title = f"{cfg['title']} (Synthetic)"
        party_a = cfg["party_a"]
        party_b = cfg["party_b"]

        # Build 10-12 structured clauses per contract
        clauses = [
            ("1", "Preamble & Recitals", f"This {cfg['title']} is entered into on this 1st day of April 2024 by and between {party_a} ('Party A') and {party_b} ('Party B'). WHEREAS, the parties desire to establish legal relations subject to the terms hereinafter."),
            ("2", "Scope of Engagement & Deliverables", f"Party B shall perform services and deliver contractual milestones in strict accordance with the specifications detailed in Schedule A attached hereto."),
            ("3", "Term and Termination for Convenience", f"This Agreement commences on the Effective Date and continues for a period of two (2) years. Either party may terminate this Agreement without cause by providing {cfg['term_days']} days prior written notice to the other party." if cfg['term_days'] > 0 else "This Agreement is binding and irrevocable upon execution and may not be terminated for convenience."),
            ("4", "Fees, Invoicing, and Payment Terms", "Invoices shall be rendered on a monthly milestone basis. Undisputed amounts shall be paid within thirty (30) calendar days of invoice receipt. Late payments shall accrue interest at 1.5% per month."),
            ("5", "Confidentiality Obligations", f"Each party agrees to safeguard Confidential Information of the other with reasonable care. These confidentiality obligations shall survive termination of this Agreement for a period of {cfg['confidentiality_years']} years."),
            ("6", "Intellectual Property Rights", "All Work Product, discoveries, developments, and inventions created under this Agreement shall vest exclusively with Party A upon payment of fees. Party B hereby executes an absolute assignment of all worldwide rights."),
            ("7", "Indemnification & Defense", f"Indemnification standard: {cfg['indemnity']}. The indemnifying party shall defend, indemnify, and hold harmless the other party against third-party claims, costs, and reasonable attorney fees."),
            ("8", "Limitation of Liability", f"Limitation of Liability: {cfg['liability_cap']}. Neither party shall be liable for consequential, incidental, special, or punitive damages under any theory of contract, tort, or strict liability."),
            ("9", "Restrictive Covenants & Non-Compete", f"During the term and for a period of {cfg['non_compete_months']} months following termination, neither party shall directly solicit the key personnel or engage in directly competing business within the restricted territory." if cfg['non_compete_months'] > 0 else "No restrictive non-compete covenants shall apply following the termination of this Agreement."),
            ("10", "Audit and Inspection Rights", f"Party A reserves the right to audit books, technical logs, and security controls upon providing not less than {cfg['audit_notice_days']} business days prior written notice." if cfg['audit_notice_days'] > 0 else "Audit rights are limited to mutual certified annual financial statements."),
            ("11", "Governing Law & Dispute Resolution", f"Governing Law: {cfg['governing_law']}. Dispute Resolution: {cfg['dispute']}."),
            ("12", "Entire Agreement & Severability", "This Agreement constitutes the entire understanding between the parties and supersedes all prior negotiations. Any modification must be in writing and signed by authorized signatories."),
        ]

        text_lines = [
            f"# {title}",
            f"BETWEEN: {party_a}",
            f"AND: {party_b}",
            f"Category: {cfg['cat']}",
            f"Effective Date: 2024-04-01\n",
        ]

        for c_num, c_title, c_text in clauses:
            sec_id = f"{doc_id}-CLAUSE-{c_num}"
            all_sections.append({
                "section_id": sec_id,
                "document_id": doc_id,
                "section_number": c_num,
                "title": c_title,
                "text": c_text,
                "source_authority": SourceAuthority.SYNTHETIC.value,
                "synthetic": True,
                "page_start": 1 if int(c_num) <= 6 else 2,
                "page_end": 1 if int(c_num) <= 6 else 2,
            })
            text_lines.append(f"Clause {c_num}. {c_title}\n{c_text}\n")

        raw_text = "\n".join(text_lines)

        documents.append({
            "document_id": doc_id,
            "title": title,
            "document_type": DocumentType.CONTRACT.value,
            "source_authority": SourceAuthority.SYNTHETIC.value,
            "source_name": "LegalLens Synthetic Corpus",
            "source_url": None,
            "synthetic": True,
            "legal_domain": LegalDomain.CONTRACT_LAW.value,
            "secondary_domains": [LegalDomain.COMMERCIAL_CORPORATE.value],
            "act_year": 2024,
            "act_number": None,
            "jurisdiction": "Union of Bharat (Synthetic)",
            "parties": [party_a, party_b],
            "document_version_group_id": f"vg-{doc_id.lower()}",
            "version_label": "v1.0",
            "publication_date": "2024-04-01",
            "effective_date": "2024-04-01",
            "status": DocumentStatus.ACTIVE.value,
            "section_count": len(clauses),
            "raw_text": raw_text,
        })

        structured_contracts.append({
            "contract_id": doc_id,
            "title": title,
            "category": cfg["cat"],
            "party_a": party_a,
            "party_b": party_b,
            "effective_date": "2024-04-01",
            "termination_notice_days": cfg["term_days"],
            "liability_cap": cfg["liability_cap"],
            "indemnity_type": cfg["indemnity"],
            "governing_law": cfg["governing_law"],
            "dispute_forum": cfg["dispute"],
            "confidentiality_duration_years": cfg["confidentiality_years"],
            "non_compete_duration_months": cfg["non_compete_months"],
            "audit_notice_days": cfg["audit_notice_days"],
            "synthetic": True,
            "source_authority": SourceAuthority.SYNTHETIC.value,
        })

    return documents, all_sections, structured_contracts
