"""
pipeline/synthetic/judgment_builder.py
======================================
Generates 20 realistic synthetic judicial decisions from fictional courts.
Includes facts, framed legal issues, arguments, analysis citing synthetic Acts, and final orders.
Guarantees NO real judges, real courts, real litigants, or real case citations.
"""

from __future__ import annotations

from typing import Any, Dict, List, Tuple

from pipeline.core.metadata import DocumentType, LegalDomain, SourceAuthority, DocumentStatus
from pipeline.synthetic.taxonomy import SYNTHETIC_COURTS, SYNTHETIC_COMPANIES

JUDGMENT_SPECS = [
    {
        "id": "SYN-JUDG-001",
        "case_no": "SYNTHETIC-WP-2025-1042",
        "court": "High Court of Dakshin Pradesh (Synthetic)",
        "bench": "Hon'ble Justice V. S. Rao (Synthetic) and Hon'ble Justice P. K. Iyer (Synthetic)",
        "petitioner": "Aarav Technologies Pvt. Ltd. (Synthetic)",
        "respondent": "Digital Services Regulatory Authority of Bharat (Synthetic)",
        "domain": LegalDomain.IT_CYBER_LAW.value,
        "cited_act": "SYN-ACT-001",
        "year": 2025,
        "date": "2025-06-12",
        "issue": "Whether Section 14 of the Digital Services Accountability Act permits algorithmic code deposit without prior non-disclosure safeguards.",
        "holding": "The Court held that proprietary algorithmic deposits under Section 14 must be secured in cryptographic escrow and cannot be inspected without notice.",
    },
    {
        "id": "SYN-JUDG-002",
        "case_no": "SYNTHETIC-COMM-APP-2024-0315",
        "court": "National Commercial Appellate Tribunal of Bharat (Synthetic)",
        "bench": "Hon'ble Justice K. L. Deshmukh (Synthetic)",
        "petitioner": "Daksha Renewable Energy Solutions Ltd. (Synthetic)",
        "respondent": "State Power Distribution Corporation of Paschim Rashtra (Synthetic)",
        "domain": LegalDomain.ELECTRICITY_ENERGY.value,
        "cited_act": "SYN-ACT-002",
        "year": 2024,
        "date": "2024-09-18",
        "issue": "Enforceability of cross-subsidy surcharge exemption under Section 11 of the Renewable Energy Grid Integration Act.",
        "holding": "Exemption under Section 11 is absolute for captive green hydrogen generators; Discom demand notices quashed.",
    },
    {
        "id": "SYN-JUDG-003",
        "case_no": "SYNTHETIC-CRIM-REV-2023-0882",
        "court": "High Court of Uttaraanchal (Synthetic)",
        "bench": "Hon'ble Justice S. C. Sen (Synthetic)",
        "petitioner": "Zenith FinTech Services Pvt. Ltd. (Synthetic)",
        "respondent": "State of Uttaraanchal & Anr. (Synthetic)",
        "domain": LegalDomain.BANKING_FINANCIAL.value,
        "cited_act": "SYN-ACT-003",
        "year": 2023,
        "date": "2023-11-20",
        "issue": "Criminal liability of recovery agency directors for after-hours automated tele-calling in violation of fair lending norms.",
        "holding": "Directors are vicariously liable under Section 22 unless demonstrated that due diligence protocols were actively audited.",
    },
    {
        "id": "SYN-JUDG-004",
        "case_no": "SYNTHETIC-PIL-2024-0044",
        "court": "High Court of Paschim Rashtra (Synthetic)",
        "bench": "Hon'ble Chief Justice M. S. Pillai (Synthetic) and Hon'ble Justice D. N. Mehta (Synthetic)",
        "petitioner": "Consumer Health Safety Collective (Synthetic)",
        "respondent": "Kaveri Healthtech Innovations Pvt. Ltd. (Synthetic)",
        "domain": LegalDomain.HEALTH_MEDICAL.value,
        "cited_act": "SYN-ACT-004",
        "year": 2024,
        "date": "2024-08-05",
        "issue": "Mandatory recall of batch Class D coronary catheters lacking GS1 UDI laser markings under Section 15.",
        "holding": "Interim injunction granted; commercial distribution restrained until complete batch traceability audit is filed.",
    },
    {
        "id": "SYN-JUDG-005",
        "case_no": "SYNTHETIC-WP-2025-2210",
        "court": "High Court of Dakshin Pradesh (Synthetic)",
        "bench": "Hon'ble Justice R. V. Menon (Synthetic)",
        "petitioner": "Suraksha Cybersecurity Systems LLP (Synthetic)",
        "respondent": "Digital Services Regulatory Authority of Bharat (Synthetic)",
        "domain": LegalDomain.EMERGING_TECHNOLOGY_AI.value,
        "cited_act": "SYN-ACT-005",
        "year": 2025,
        "date": "2025-07-22",
        "issue": "Classification of autonomous red-teaming cyber tools as high-risk artificial intelligence models under Section 6.",
        "holding": "Defensive testing models qualify for conditional sandbox exemption; administrative classification set aside for reconsideration.",
    },
    {
        "id": "SYN-JUDG-006",
        "case_no": "SYNTHETIC-IND-DISP-2023-0199",
        "court": "High Court of Purvanchal (Synthetic)",
        "bench": "Hon'ble Justice T. K. Roy (Synthetic)",
        "petitioner": "All Bharat Remote Professionals Association (Synthetic)",
        "respondent": "Pratham Software Solutions Pvt. Ltd. (Synthetic)",
        "domain": LegalDomain.EMPLOYMENT_LABOUR.value,
        "cited_act": "SYN-ACT-006",
        "year": 2023,
        "date": "2023-12-14",
        "issue": "Whether routine email monitoring outside designated shift hours violates Section 8 (Right to Disconnect).",
        "holding": "Silent monitoring and passive message dispatch during off-shift periods constitutes constructive harassment; damages awarded.",
    },
    {
        "id": "SYN-JUDG-007",
        "case_no": "SYNTHETIC-ENV-APP-2024-0052",
        "court": "Environmental Redressal Tribunal of Dakshin Pradesh (Synthetic)",
        "bench": "Hon'ble Chairperson Justice B. G. Swamy (Synthetic) and Dr. H. L. Rao, Expert Member (Synthetic)",
        "petitioner": "Green Valley Resident Welfare Forum (Synthetic)",
        "respondent": "Chaitanya Consumer Goods Ltd. (Synthetic)",
        "domain": LegalDomain.ENVIRONMENTAL_LAW.value,
        "cited_act": "SYN-ACT-007",
        "year": 2024,
        "date": "2024-05-19",
        "issue": "Unauthorized industrial groundwater pumping in critical over-exploited basin under Section 12.",
        "holding": "Industrial borewell sealed; environmental restitution penalty of ₹1.5 Crore imposed.",
    },
    {
        "id": "SYN-JUDG-008",
        "case_no": "SYNTHETIC-ARB-PET-2023-0610",
        "court": "High Court of Paschim Rashtra (Synthetic)",
        "bench": "Hon'ble Justice N. K. Joshi (Synthetic)",
        "petitioner": "Neelam Cloud Services India Ltd. (Synthetic)",
        "respondent": "Veda Data Analytics Pvt. Ltd. (Synthetic)",
        "domain": LegalDomain.ARBITRATION_ADR.value,
        "cited_act": "SYN-ACT-008",
        "year": 2023,
        "date": "2023-10-30",
        "issue": "Enforceability of an online conciliation settlement deed executed without physical notary stamps under Section 16.",
        "holding": "Digital settlement deeds with Aadhaar-eSign possess status of a court compromise decree; petition dismissed.",
    },
    {
        "id": "SYN-JUDG-009",
        "case_no": "SYNTHETIC-CRIM-MISC-2024-1188",
        "court": "High Court of Uttaraanchal (Synthetic)",
        "bench": "Hon'ble Justice K. S. Bedi (Synthetic)",
        "petitioner": "Chief Information Security Officer, Neelam Cloud (Synthetic)",
        "respondent": "Central Cybersecurity Emergency Coordination Cell (Synthetic)",
        "domain": LegalDomain.IT_CYBER_LAW.value,
        "cited_act": "SYN-ACT-009",
        "year": 2024,
        "date": "2024-11-12",
        "issue": "Whether a 9-hour delay in reporting a zero-day intrusion constitutes willful default under Section 12.",
        "holding": "Delay of 3 hours beyond 6-hour statutory window condoned due to emergency air-gapping measures; fine set aside.",
    },
    {
        "id": "SYN-JUDG-010",
        "case_no": "SYNTHETIC-INSOLV-APP-2024-0012",
        "court": "National Commercial Appellate Tribunal of Bharat (Synthetic)",
        "bench": "Hon'ble Justice S. J. Mukhopadhyay (Synthetic)",
        "petitioner": "Samarth Engineering Consultants Pvt. Ltd. (Synthetic)",
        "respondent": "Committee of Creditors of Bhoomi Logistics (Synthetic)",
        "domain": LegalDomain.INSOLVENCY_BANKRUPTCY.value,
        "cited_act": "SYN-ACT-010",
        "year": 2024,
        "date": "2024-04-11",
        "issue": "Validity of pre-packaged insolvency resolution plan approved by 55% majority prior to 2024 amendment.",
        "holding": "Amendments reducing voting threshold to 51% are procedural and operate retrospectively for pending approval applications.",
    },
    {
        "id": "SYN-JUDG-011",
        "case_no": "SYNTHETIC-CONS-APPEAL-2024-0441",
        "court": "Appellate Tribunal for Digital Commerce (Synthetic)",
        "bench": "Hon'ble Justice A. R. Patel (Synthetic)",
        "petitioner": "Vistara Retail Enterprises LLP (Synthetic)",
        "respondent": "Central Consumer Protection Authority of Bharat (Synthetic)",
        "domain": LegalDomain.CONSUMER_LAW.value,
        "cited_act": "SYN-ACT-011",
        "year": 2024,
        "date": "2024-12-08",
        "issue": "Whether pre-checked express shipping check-boxes constitute illegal dark patterns under Section 9.",
        "holding": "Pre-ticked opt-in boxes violate explicit consumer choice; refund of convenience fee to 45,000 customers ordered.",
    },
    {
        "id": "SYN-JUDG-012",
        "case_no": "SYNTHETIC-WP-2025-0902",
        "court": "High Court of Dakshin Pradesh (Synthetic)",
        "bench": "Hon'ble Justice M. K. Chari (Synthetic)",
        "petitioner": "Pavan Logistics & Freight Corp. (Synthetic)",
        "respondent": "National Electronic Toll and Highway Safety Directorate (Synthetic)",
        "domain": LegalDomain.MOTOR_VEHICLE_TRANSPORT.value,
        "cited_act": "SYN-ACT-012",
        "year": 2025,
        "date": "2025-05-24",
        "issue": "Liability allocation between fleet operator and AI software vendor following autonomous freight collision.",
        "holding": "Primary strict liability rests with registered owner under Section 19, with right to claim indemnification from software provider.",
    },
    {
        "id": "SYN-JUDG-013",
        "case_no": "SYNTHETIC-COMM-SUIT-2023-0301",
        "court": "High Court of Paschim Rashtra (Synthetic)",
        "bench": "Hon'ble Justice G. V. Hegde (Synthetic)",
        "petitioner": "Bhoomi Infrastructure & Logistics LLP (Synthetic)",
        "respondent": "Paschim Agro Products Cooperative (Synthetic)",
        "domain": LegalDomain.COMMERCIAL_CORPORATE.value,
        "cited_act": "SYN-ACT-013",
        "year": 2023,
        "date": "2023-09-15",
        "issue": "Right of cold storage operator to exercise lien on stored horticultural goods for unpaid thermal tariff charges.",
        "holding": "Lien under Section 14 is subject to prior perishable preservation protocols; auction permitted after 7-day cure notice.",
    },
    {
        "id": "SYN-JUDG-014",
        "case_no": "SYNTHETIC-WP-2024-3310",
        "court": "High Court of Paschim Rashtra (Synthetic)",
        "bench": "Hon'ble Justice F. H. Talyarkhan (Synthetic)",
        "petitioner": "Dr. R. Ananth & Ors. (Synthetic)",
        "respondent": "State Medical Council of Paschim Rashtra (Synthetic)",
        "domain": LegalDomain.HEALTH_MEDICAL.value,
        "cited_act": "SYN-ACT-014",
        "year": 2024,
        "date": "2024-07-16",
        "issue": "Physician duty to upload patient discharge summaries to national health exchange without patient consent.",
        "holding": "Mandatory interoperability under Section 7 is strictly governed by patient dynamic consent; unilateral upload without opt-in quashed.",
    },
    {
        "id": "SYN-JUDG-015",
        "case_no": "SYNTHETIC-RERA-REV-2023-0112",
        "court": "High Court of Uttaraanchal (Synthetic)",
        "bench": "Hon'ble Justice Y. N. Tiwari (Synthetic)",
        "petitioner": "Skyline Heights Apartment Owners Association (Synthetic)",
        "respondent": "Apex Realcon Projects LLP (Synthetic)",
        "domain": LegalDomain.PROPERTY_REAL_ESTATE.value,
        "cited_act": "SYN-ACT-015",
        "year": 2023,
        "date": "2023-08-22",
        "issue": "Diversion of funds from project escrow account for acquisition of unrelated land parcels under Section 13.",
        "holding": "Escrow funds are held in trust for construction milestones; directors ordered to deposit ₹8.2 Crore within 30 days.",
    },
    {
        "id": "SYN-JUDG-016",
        "case_no": "SYNTHETIC-WP-2025-1845",
        "court": "High Court of Paschim Rashtra (Synthetic)",
        "bench": "Hon'ble Justice C. M. Rao (Synthetic)",
        "petitioner": "BioHelix Innovations Pvt. Ltd. (Synthetic)",
        "respondent": "Medical Devices Quality and Traceability Board (Synthetic)",
        "domain": LegalDomain.HEALTH_MEDICAL.value,
        "cited_act": "SYN-ACT-016",
        "year": 2025,
        "date": "2025-03-10",
        "issue": "Suspension of gene synthesizer import license for omission of biosecurity customer screening registry.",
        "holding": "Biosecurity compliance under Section 8 is a condition precedent to import clearance; suspension upheld.",
    },
    {
        "id": "SYN-JUDG-017",
        "case_no": "SYNTHETIC-TEL-APPEAL-2024-0005",
        "court": "Appellate Tribunal for Digital Commerce (Synthetic)",
        "bench": "Hon'ble Justice K. R. Vyas (Synthetic)",
        "petitioner": "Bharat Fiber & Broadband Corp. (Synthetic)",
        "respondent": "Department of Telecommunications and Cyber Infrastructure (Synthetic)",
        "domain": LegalDomain.TELECOMMUNICATIONS.value,
        "cited_act": "SYN-ACT-017",
        "year": 2024,
        "date": "2024-10-04",
        "issue": "Dispute over dynamic spectrum sharing fees and interference penalty calculation under Section 15.",
        "holding": "Administrative calculation of interference penalty held arbitrary; remanded for reassessment using objective RF metrics.",
    },
    {
        "id": "SYN-JUDG-018",
        "case_no": "SYNTHETIC-PIL-2024-0091",
        "court": "Environmental Redressal Tribunal of Dakshin Pradesh (Synthetic)",
        "bench": "Hon'ble Chairperson Justice B. G. Swamy (Synthetic)",
        "petitioner": "Clean Earth Foundation (Synthetic)",
        "respondent": "Chaitanya Consumer Goods Ltd. & Ors. (Synthetic)",
        "domain": LegalDomain.ENVIRONMENTAL_LAW.value,
        "cited_act": "SYN-ACT-018",
        "year": 2024,
        "date": "2024-06-30",
        "issue": "Failure to achieve 50% post-consumer recycled content in multi-layer packaging under Section 10.",
        "holding": "Environmental compensation of ₹45 Lakh imposed with direction to procure verified EPR credits within 60 days.",
    },
    {
        "id": "SYN-JUDG-019",
        "case_no": "SYNTHETIC-COMP-APPEAL-2025-0019",
        "court": "National Commercial Appellate Tribunal of Bharat (Synthetic)",
        "bench": "Hon'ble Justice D. S. Mathur (Synthetic)",
        "petitioner": "Mitra Digital Payment Solutions Ltd. (Synthetic)",
        "respondent": "Competition Commission of Bharat (Synthetic)",
        "domain": LegalDomain.COMPETITION_LAW.value,
        "cited_act": "SYN-ACT-021",
        "year": 2025,
        "date": "2025-08-14",
        "issue": "Tying and bundling of app store billing with proprietary mobile payment gateway under Section 12.",
        "holding": "Exclusivity mandate constitutes abuse of market dominance; penalty of 3% average global turnover confirmed.",
    },
    {
        "id": "SYN-JUDG-020",
        "case_no": "SYNTHETIC-LOK-ADALAT-2023-0711",
        "court": "Dakshin Pradesh Legal Aid and Literacy Authority (Synthetic)",
        "bench": "Hon'ble Presiding Judge S. R. Nambiar (Synthetic) and Smt. L. Sundaram, Advocate Conciliator (Synthetic)",
        "petitioner": "Ramanathan Pillai (Synthetic)",
        "respondent": "Dakshin Power Distribution Co. (Synthetic)",
        "domain": LegalDomain.HUMAN_RIGHTS.value,
        "cited_act": "SYN-ACT-024",
        "year": 2023,
        "date": "2023-11-05",
        "issue": "Conciliation settlement of disputed agrarian electricity arrears under Section 15.",
        "holding": "Compromise recorded; waiver of 70% surcharge granted with 6-month installment facility; award finalized as unappealable decree.",
    },
]

def generate_synthetic_judgments() -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Generates 20 synthetic court judgments with structured facts, issues, arguments, analysis, and orders."""
    documents: List[Dict[str, Any]] = []
    all_sections: List[Dict[str, Any]] = []

    for item in JUDGMENT_SPECS:
        doc_id = item["id"]
        title = f"{item['petitioner']} v. {item['respondent']}"

        sections = [
            ("1", "Case Details and Coram", f"In the {item['court']}.\nCase Number: {item['case_no']}.\nBefore: {item['bench']}.\nDate of Pronouncement: {item['date']}."),
            ("2", "Factual Matrix", f"The petitioner, {item['petitioner']}, approached this Court seeking appropriate writs and reliefs against {item['respondent']} in respect of actions arising under {item['cited_act']}. The petitioner contended that statutory authorities acted outside their jurisdiction and in violation of natural justice."),
            ("3", "Issues for Determination", f"The primary question for determination before this Court is: {item['issue']}"),
            ("4", "Submissions of the Parties", f"Senior Counsel appearing for the petitioner argued that statutory provisions under {item['cited_act']} must be construed strictly to protect operational certainty. Learned Counsel for the respondent submitted that regulatory powers are designed to safeguard public interest and market integrity."),
            ("5", "Judicial Analysis and Reasoning", f"Having considered the statutory provisions under {item['cited_act']} and the rival submissions, the Court observes that regulatory compliance must be balanced with procedural fairness. Specifically: {item['holding']}"),
            ("6", "Final Order and Directions", f"In view of the above conclusions, the petition is disposed of with the following binding directions: (1) The impugned administrative communication is modified in terms of the holding herein; (2) Parties shall bear their own costs; (3) Compliance report shall be filed within four weeks."),
        ]

        text_lines = [
            f"# {title}",
            f"Court: {item['court']}",
            f"Case No: {item['case_no']}",
            f"Bench: {item['bench']}",
            f"Date of Decision: {item['date']}",
            f"Cited Enactment: {item['cited_act']}\n",
        ]

        for s_num, s_title, s_text in sections:
            sec_id = f"{doc_id}-SEC-{s_num}"
            all_sections.append({
                "section_id": sec_id,
                "document_id": doc_id,
                "section_number": s_num,
                "title": s_title,
                "text": s_text,
                "source_authority": SourceAuthority.SYNTHETIC.value,
                "synthetic": True,
                "page_start": int(s_num),
                "page_end": int(s_num),
            })
            text_lines.append(f"Section {s_num}. {s_title}\n{s_text}\n")

        raw_text = "\n".join(text_lines)

        documents.append({
            "document_id": doc_id,
            "title": title,
            "document_type": DocumentType.JUDGMENT.value,
            "source_authority": SourceAuthority.SYNTHETIC.value,
            "source_name": "LegalLens Synthetic Corpus",
            "source_url": None,
            "synthetic": True,
            "legal_domain": item["domain"],
            "secondary_domains": [],
            "act_year": item["year"],
            "act_number": item["case_no"],
            "jurisdiction": "Union of Bharat (Synthetic)",
            "court": item["court"],
            "bench": item["bench"],
            "petitioner": item["petitioner"],
            "respondent": item["respondent"],
            "parent_act_id": item["cited_act"],
            "document_version_group_id": f"vg-{doc_id.lower()}",
            "version_label": "v1.0",
            "publication_date": item["date"],
            "effective_date": item["date"],
            "status": DocumentStatus.ACTIVE.value,
            "section_count": len(sections),
            "raw_text": raw_text,
        })

    return documents, all_sections
