"""
pipeline/synthetic/rule_builder.py
==================================
Generates 40 synthetic Rules and Regulations referencing parent synthetic Acts.
Each rule includes subrules, schedules, compliance forms, and fee provisions.
"""

from __future__ import annotations

import random
from typing import Any, Dict, List, Tuple

from pipeline.core.metadata import DocumentType, LegalDomain, SourceAuthority, DocumentStatus
from pipeline.synthetic.taxonomy import SYNTHETIC_MINISTRIES, SYNTHETIC_AUTHORITIES

# 40 synthetic rule definitions mapped across the 25 synthetic acts
RULE_SPECS = [
    {
        "id": "SYN-RULE-001",
        "parent_act_id": "SYN-ACT-001",
        "title": "Digital Platform Intermediary Due Diligence Rules, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.IT_CYBER_LAW.value,
        "authority": "Digital Services Regulatory Authority of Bharat (Synthetic)",
        "ministry": "Ministry of Digital Economy and Innovation (Synthetic)",
        "topics": ["take-down notice timeline", "grievance officer monthly report", "automated screening thresholds"],
    },
    {
        "id": "SYN-RULE-002",
        "parent_act_id": "SYN-ACT-001",
        "title": "Algorithmic Transparency and Audit Procedures Rules, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.IT_CYBER_LAW.value,
        "authority": "Digital Services Regulatory Authority of Bharat (Synthetic)",
        "ministry": "Ministry of Digital Economy and Innovation (Synthetic)",
        "topics": ["code repository deposit", "independent auditor empanelment", "explainability criteria"],
    },
    {
        "id": "SYN-RULE-003",
        "parent_act_id": "SYN-ACT-002",
        "title": "Renewable Purchase Obligation Compliance and Verification Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.ELECTRICITY_ENERGY.value,
        "authority": "National Clean Energy Grid Council (Synthetic)",
        "ministry": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "topics": ["green certificates registry", "shortfall penalty rate", "captive power plant verification"],
    },
    {
        "id": "SYN-RULE-004",
        "parent_act_id": "SYN-ACT-002",
        "title": "Open Access Transmission Tariff Determination Regulations, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.ELECTRICITY_ENERGY.value,
        "authority": "National Clean Energy Grid Council (Synthetic)",
        "ministry": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "topics": ["cross-subsidy surcharge formula", "wheeling losses benchmark", "interconnection application fee"],
    },
    {
        "id": "SYN-RULE-005",
        "parent_act_id": "SYN-ACT-003",
        "title": "Digital Lending Key Fact Statement Disclosures Rules, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.BANKING_FINANCIAL.value,
        "authority": "National Fair Lending and Credit Commission (Synthetic)",
        "ministry": "Ministry of Commerce and Fair Competition (Synthetic)",
        "topics": ["all-inclusive APR calculation", "cooling-off disbursement refund", "tele-calling permissible hours"],
    },
    {
        "id": "SYN-RULE-006",
        "parent_act_id": "SYN-ACT-003",
        "title": "Debt Recovery Agency Accreditation and Conduct Regulations, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.BANKING_FINANCIAL.value,
        "authority": "National Fair Lending and Credit Commission (Synthetic)",
        "ministry": "Ministry of Commerce and Fair Competition (Synthetic)",
        "topics": ["background check protocols", "prohibition on harassment and threats", "voice recording retention"],
    },
    {
        "id": "SYN-RULE-007",
        "parent_act_id": "SYN-ACT-004",
        "title": "Medical Devices Unique Identifier and Registration Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.HEALTH_MEDICAL.value,
        "authority": "Medical Devices Quality and Traceability Board (Synthetic)",
        "ministry": "Ministry of Health Technologies and Biosecurity (Synthetic)",
        "topics": ["barcode standards", "implant registry upload", "sterilization record retention"],
    },
    {
        "id": "SYN-RULE-008",
        "parent_act_id": "SYN-ACT-004",
        "title": "Medical Implant Adverse Event Reporting Regulations, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.HEALTH_MEDICAL.value,
        "authority": "Medical Devices Quality and Traceability Board (Synthetic)",
        "ministry": "Ministry of Health Technologies and Biosecurity (Synthetic)",
        "topics": ["72-hour fatal event intimation", "recall protocol timeline", "patient compensation formula"],
    },
    {
        "id": "SYN-RULE-009",
        "parent_act_id": "SYN-ACT-005",
        "title": "High-Risk Artificial Intelligence Model Assessment Regulations, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.EMERGING_TECHNOLOGY_AI.value,
        "authority": "Digital Services Regulatory Authority of Bharat (Synthetic)",
        "ministry": "Ministry of Digital Economy and Innovation (Synthetic)",
        "topics": ["red-teaming criteria", "bias mitigation benchmarks", "model weights escrow"],
    },
    {
        "id": "SYN-RULE-010",
        "parent_act_id": "SYN-ACT-005",
        "title": "Synthetic Media Provenance and Watermarking Rules, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.EMERGING_TECHNOLOGY_AI.value,
        "authority": "Digital Services Regulatory Authority of Bharat (Synthetic)",
        "ministry": "Ministry of Digital Economy and Innovation (Synthetic)",
        "topics": ["cryptographic metadata embedding", "audio deepfake identifier", "exemption for parody"],
    },
    {
        "id": "SYN-RULE-011",
        "parent_act_id": "SYN-ACT-006",
        "title": "Remote Worker Ergonomics and Workstation Subsidy Rules, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.EMPLOYMENT_LABOUR.value,
        "authority": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "ministry": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "topics": ["chair and monitor reimbursement schedule", "annual physical inspection waiver", "home power allowance"],
    },
    {
        "id": "SYN-RULE-012",
        "parent_act_id": "SYN-ACT-006",
        "title": "Right to Disconnect Protocol and Overtime Compensation Regulations, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.EMPLOYMENT_LABOUR.value,
        "authority": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "ministry": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "topics": ["quiet hours 8pm to 8am", "emergency response overtime multiplier", "logging off compliance tracking"],
    },
    {
        "id": "SYN-RULE-013",
        "parent_act_id": "SYN-ACT-007",
        "title": "Rainwater Harvesting Standard Specifications and Audit Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.ENVIRONMENTAL_LAW.value,
        "authority": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "ministry": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "topics": ["catchment area calculation", "filtration unit design", "recharge well depth limit"],
    },
    {
        "id": "SYN-RULE-014",
        "parent_act_id": "SYN-ACT-007",
        "title": "Industrial Borewell Extraction Metering and Tariff Regulations, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.ENVIRONMENTAL_LAW.value,
        "authority": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "ministry": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "topics": ["telemetric meter installation", "critical basin surcharge", "effluent injection prohibition"],
    },
    {
        "id": "SYN-RULE-015",
        "parent_act_id": "SYN-ACT-008",
        "title": "Online Dispute Resolution Provider Accreditation Regulations, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.ARBITRATION_ADR.value,
        "authority": "Consumer Protection and Redressal Council (Synthetic)",
        "ministry": "Department of Consumer Empowerment (Synthetic)",
        "topics": ["arbitrator qualification", "video recording encryption", "21-day expedited hearing schedule"],
    },
    {
        "id": "SYN-RULE-016",
        "parent_act_id": "SYN-ACT-008",
        "title": "Automated Mediation and Settlement Enforceability Rules, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.ARBITRATION_ADR.value,
        "authority": "Consumer Protection and Redressal Council (Synthetic)",
        "ministry": "Department of Consumer Empowerment (Synthetic)",
        "topics": ["digital signature verification", "stamp duty payment portal", "execution as civil court decree"],
    },
    {
        "id": "SYN-RULE-017",
        "parent_act_id": "SYN-ACT-009",
        "title": "Critical Infrastructure Cyber Incident Intimation Regulations, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.IT_CYBER_LAW.value,
        "authority": "Central Cybersecurity Emergency Coordination Cell (Synthetic)",
        "ministry": "Department of Telecommunications and Cyber Infrastructure (Synthetic)",
        "topics": ["6-hour reporting deadline", "forensic log preservation 180 days", "ransomware payment reporting"],
    },
    {
        "id": "SYN-RULE-018",
        "parent_act_id": "SYN-ACT-009",
        "title": "Third-Party Vendor Cybersecurity Assessment Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.IT_CYBER_LAW.value,
        "authority": "Central Cybersecurity Emergency Coordination Cell (Synthetic)",
        "ministry": "Department of Telecommunications and Cyber Infrastructure (Synthetic)",
        "topics": ["supply chain security tiering", "annual penetration testing", "vulnerability disclosure timeline"],
    },
    {
        "id": "SYN-RULE-019",
        "parent_act_id": "SYN-ACT-010",
        "title": "Pre-Packaged Insolvency Application and Notice Rules, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.INSOLVENCY_BANKRUPTCY.value,
        "authority": "Ministry of Commerce and Fair Competition (Synthetic)",
        "ministry": "Ministry of Commerce and Fair Competition (Synthetic)",
        "topics": ["Form MSME-1 submission", "base resolution plan disclosure", "operational creditor objection window"],
    },
    {
        "id": "SYN-RULE-020",
        "parent_act_id": "SYN-ACT-010",
        "title": "Micro-Enterprise Resolution Professional Fee and Conduct Regulations, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.INSOLVENCY_BANKRUPTCY.value,
        "authority": "Ministry of Commerce and Fair Competition (Synthetic)",
        "ministry": "Ministry of Commerce and Fair Competition (Synthetic)",
        "topics": ["capped fee structure", "conflict of interest declaration", "interim finance facilitation"],
    },
    {
        "id": "SYN-RULE-021",
        "parent_act_id": "SYN-ACT-011",
        "title": "E-Commerce Dark Patterns Detection and Prohibition Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.CONSUMER_LAW.value,
        "authority": "Consumer Protection and Redressal Council (Synthetic)",
        "ministry": "Department of Consumer Empowerment (Synthetic)",
        "topics": ["false urgency countdown clocks", "basket sneaking penalties", "subscription cancellation difficulty test"],
    },
    {
        "id": "SYN-RULE-022",
        "parent_act_id": "SYN-ACT-011",
        "title": "Consumer Product Repairability Index and Spare Parts Regulations, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.CONSUMER_LAW.value,
        "authority": "Consumer Protection and Redressal Council (Synthetic)",
        "ministry": "Department of Consumer Empowerment (Synthetic)",
        "topics": ["repair manual public access", "spare parts availability 7 years", "diagnostic software release"],
    },
    {
        "id": "SYN-RULE-023",
        "parent_act_id": "SYN-ACT-012",
        "title": "Autonomous Commercial Vehicle Testing and Safety Pilot Rules, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.MOTOR_VEHICLE_TRANSPORT.value,
        "authority": "National Electronic Toll and Highway Safety Directorate (Synthetic)",
        "ministry": "Ministry of Urban Infrastructure and Transport (Synthetic)",
        "topics": ["safety driver qualifications", "disengagement logging requirements", "minimum third-party liability cover"],
    },
    {
        "id": "SYN-RULE-024",
        "parent_act_id": "SYN-ACT-012",
        "title": "Electric Commercial Fleet Battery Swapping Safety Standards Regulations, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.MOTOR_VEHICLE_TRANSPORT.value,
        "authority": "National Electronic Toll and Highway Safety Directorate (Synthetic)",
        "ministry": "Ministry of Urban Infrastructure and Transport (Synthetic)",
        "topics": ["thermal runaway sensor standards", "connector interoperability", "battery recycling manifest"],
    },
    {
        "id": "SYN-RULE-025",
        "parent_act_id": "SYN-ACT-013",
        "title": "Agricultural Cold Chain Grid Subsidy and Energy Standard Rules, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.COMMERCIAL_CORPORATE.value,
        "authority": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "ministry": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "topics": ["solar packhouse capital subsidy", "temperature logging calibration", "perishable crop spoilage insurance"],
    },
    {
        "id": "SYN-RULE-026",
        "parent_act_id": "SYN-ACT-014",
        "title": "Electronic Health Record Interoperability and Consent Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.HEALTH_MEDICAL.value,
        "authority": "Medical Devices Quality and Traceability Board (Synthetic)",
        "ministry": "Ministry of Health Technologies and Biosecurity (Synthetic)",
        "topics": ["FHIR compliance mandate", "patient consent manager integration", "de-identified research dataset access"],
    },
    {
        "id": "SYN-RULE-027",
        "parent_act_id": "SYN-ACT-015",
        "title": "Real Estate Escrow Account Monitoring and Disbursement Rules, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.PROPERTY_REAL_ESTATE.value,
        "authority": "Ministry of Urban Infrastructure and Transport (Synthetic)",
        "ministry": "Ministry of Urban Infrastructure and Transport (Synthetic)",
        "topics": ["engineer stage completion certificate", "architect verification upload", "prohibition on promotional expenditure"],
    },
    {
        "id": "SYN-RULE-028",
        "parent_act_id": "SYN-ACT-016",
        "title": "Synthetic Gene and Biosecurity Screening Rules, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.HEALTH_MEDICAL.value,
        "authority": "Medical Devices Quality and Traceability Board (Synthetic)",
        "ministry": "Ministry of Health Technologies and Biosecurity (Synthetic)",
        "topics": ["customer vetting protocol", "pathogen sequence red-flag database", "dual-use equipment export permit"],
    },
    {
        "id": "SYN-RULE-029",
        "parent_act_id": "SYN-ACT-017",
        "title": "Telecommunications Spectrum Sharing and Dynamic Allocation Regulations, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.TELECOMMUNICATIONS.value,
        "authority": "Department of Telecommunications and Cyber Infrastructure (Synthetic)",
        "ministry": "Department of Telecommunications and Cyber Infrastructure (Synthetic)",
        "topics": ["spectrum broker platform", "interference management protocol", "rural coverage credit calculation"],
    },
    {
        "id": "SYN-RULE-030",
        "parent_act_id": "SYN-ACT-018",
        "title": "Industrial Circular Economy and Extended Producer Responsibility Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.ENVIRONMENTAL_LAW.value,
        "authority": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "ministry": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "topics": ["post-consumer recycled plastic target", "take-back collection centers", "recycler emission compliance"],
    },
    {
        "id": "SYN-RULE-031",
        "parent_act_id": "SYN-ACT-019",
        "title": "Digital Higher Education Credit Transfer and Equivalence Regulations, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.EDUCATION_LAW.value,
        "authority": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "ministry": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "topics": ["academic bank of credits", "virtual lab accreditation", "proctored examination security"],
    },
    {
        "id": "SYN-RULE-032",
        "parent_act_id": "SYN-ACT-020",
        "title": "Drone Logistics Air Corridors and Geofencing Regulations, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.MOTOR_VEHICLE_TRANSPORT.value,
        "authority": "National Electronic Toll and Highway Safety Directorate (Synthetic)",
        "ministry": "Ministry of Urban Infrastructure and Transport (Synthetic)",
        "topics": ["green zone flight registration", "no-fly hospital and airport buffers", "payload jettison emergency protocol"],
    },
    {
        "id": "SYN-RULE-033",
        "parent_act_id": "SYN-ACT-021",
        "title": "Fair Competition in Digital Markets Merger Notification Rules, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.COMPETITION_LAW.value,
        "authority": "Ministry of Commerce and Fair Competition (Synthetic)",
        "ministry": "Ministry of Commerce and Fair Competition (Synthetic)",
        "topics": ["deal value threshold ₹2000 crore", "network effect dominance index", "gun jumping penalties"],
    },
    {
        "id": "SYN-RULE-034",
        "parent_act_id": "SYN-ACT-022",
        "title": "National Green Hydrogen Standard and Carbon Offsetting Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.ELECTRICITY_ENERGY.value,
        "authority": "National Clean Energy Grid Council (Synthetic)",
        "ministry": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "topics": ["2 kg CO2 per kg H2 lifecycle limit", "water consumption certification", "green certificate trading"],
    },
    {
        "id": "SYN-RULE-035",
        "parent_act_id": "SYN-ACT-023",
        "title": "Special Economic Zone Cross-Border Data Flow Regulations, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.COMMERCIAL_CORPORATE.value,
        "authority": "Digital Services Regulatory Authority of Bharat (Synthetic)",
        "ministry": "Ministry of Digital Economy and Innovation (Synthetic)",
        "topics": ["standard contractual clauses approval", "financial cloud node localisation", "safe harbor audit"],
    },
    {
        "id": "SYN-RULE-036",
        "parent_act_id": "SYN-ACT-024",
        "title": "Automated Legal Aid Clinic Operational Protocols and Empanelment Rules, 2023 (Synthetic)",
        "year": 2023,
        "domain": LegalDomain.HUMAN_RIGHTS.value,
        "authority": "Dakshin Pradesh Legal Aid and Literacy Authority (Synthetic)",
        "ministry": "Ministry of Citizen Welfare and Legal Services (Synthetic)",
        "topics": ["paralegal volunteer roster", "kiosk technical specs", "indigent assistance threshold"],
    },
    {
        "id": "SYN-RULE-037",
        "parent_act_id": "SYN-ACT-025",
        "title": "Municipal Biogas Grid Interconnection and Quality Standards Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.ENVIRONMENTAL_LAW.value,
        "authority": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "ministry": "Ministry of Clean Energy and Climate Transition (Synthetic)",
        "topics": ["methane purity percentage minimum 90%", "odorisation requirement", "pipeline pressure limits"],
    },
    {
        "id": "SYN-RULE-038",
        "parent_act_id": "SYN-ACT-001",
        "title": "Digital Redressal Appellate Forum Procedural Regulations, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.ADMINISTRATIVE_LAW.value,
        "authority": "Appellate Tribunal for Digital Commerce (Synthetic)",
        "ministry": "Ministry of Digital Economy and Innovation (Synthetic)",
        "topics": ["30-day appeal limitation", "stay order conditional deposit", "virtual hearing norms"],
    },
    {
        "id": "SYN-RULE-039",
        "parent_act_id": "SYN-ACT-003",
        "title": "Credit Bureau Algorithmic Scoring Dispute Resolution Rules, 2024 (Synthetic)",
        "year": 2024,
        "domain": LegalDomain.BANKING_FINANCIAL.value,
        "authority": "National Fair Lending and Credit Commission (Synthetic)",
        "ministry": "Ministry of Commerce and Fair Competition (Synthetic)",
        "topics": ["15-day dispute rectification", "error compensation ₹100 per day", "prohibition on predatory score sharing"],
    },
    {
        "id": "SYN-RULE-040",
        "parent_act_id": "SYN-ACT-005",
        "title": "Public Sector Automated Decision-Making Disclosure Regulations, 2025 (Synthetic)",
        "year": 2025,
        "domain": LegalDomain.ADMINISTRATIVE_LAW.value,
        "authority": "Digital Services Regulatory Authority of Bharat (Synthetic)",
        "ministry": "Ministry of Digital Economy and Innovation (Synthetic)",
        "topics": ["citizen right to human review", "welfare eligibility algorithm notice", "quarterly audit publication"],
    },
]

def generate_synthetic_rules() -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Generates 40 synthetic rules/regulations with sections."""
    documents: List[Dict[str, Any]] = []
    all_sections: List[Dict[str, Any]] = []

    for rule_meta in RULE_SPECS:
        doc_id = rule_meta["id"]
        title = rule_meta["title"]
        topics = rule_meta["topics"]
        
        # Build 10-12 rules (sections) per rule document
        rule_items = [
            ("1", "Short title and commencement", f"These rules may be called the {title}. They shall come into force on the date of their publication in the Official Gazette."),
            ("2", "Definitions", f"In these rules, unless the context otherwise requires, 'Act' means the parent enactment ({rule_meta['parent_act_id']}); 'Appellate Authority' means the competent appellate body constituted under the Act; 'Prescribed Officer' means an officer designated by the Authority."),
            ("3", "Application and Scope", f"These rules shall apply across all entities, intermediaries, manufacturers, and service providers operating within the territorial jurisdiction under {rule_meta['parent_act_id']}."),
            ("4", f"Standard Operational Procedure for {topics[0].capitalize()}", f"Every regulated entity shall implement procedures ensuring {topics[0]}. Non-compliance shall attract administrative penalties as specified in Schedule I."),
            ("5", f"Compliance Protocol for {topics[1].capitalize()}", f"Regulated entities shall file certified quarterly declarations confirming adherence to {topics[1]}. Records shall be preserved for inspection for not less than five years."),
            ("6", f"Enforcement and Monitoring of {topics[2].capitalize()}", f"The designated inspection officer shall conduct periodic random audits to verify compliance with {topics[2]}. Failure to grant access shall constitute a violation under Section 24 of {rule_meta['parent_act_id']}."),
            ("7", "Filing of Applications and Prescribed Fees", f"Every application under these rules shall be made in Form A set forth in Schedule II, accompanied by an electronic filing fee of Rupees Two Thousand Five Hundred only."),
            ("8", "Grievance Redressal and Response Timelines", f"Any aggrieved citizen or entity may submit a representation. The designated grievance cell shall acknowledge receipt within 24 hours and issue a reasoned written response within twenty-one days."),
            ("9", "Appeals and Stay Provisions", f"An appeal against any penalty order or rejection under these rules may be preferred to the Appellate Authority within thirty days from the date of communication of the order."),
            ("10", "Penalties for Continued Default", f"Where any contravention continues after the initial notice period, an additional daily penalty of Rupees One Thousand shall be levied for each day during which the default persists."),
        ]

        text_lines = [
            f"# {title}",
            f"[G.S.R. {random.randint(100, 999)}(E)]",
            f"In exercise of the powers conferred by Section 25 of {rule_meta['parent_act_id']}, the Central Government hereby makes the following rules:\n",
        ]

        for r_num, r_title, r_text in rule_items:
            sec_id = f"{doc_id}-RULE-{r_num}"
            all_sections.append({
                "section_id": sec_id,
                "document_id": doc_id,
                "section_number": r_num,
                "title": r_title,
                "text": r_text,
                "source_authority": SourceAuthority.SYNTHETIC.value,
                "synthetic": True,
                "page_start": int(r_num),
                "page_end": int(r_num),
            })
            text_lines.append(f"Rule {r_num}. {r_title}: {r_text}\n")

        # Append Schedule I and Form A text
        text_lines.append("SCHEDULE I: Fee Structure and Penalties")
        text_lines.append("1. Routine Inspection Fee: ₹5,000")
        text_lines.append("2. Late Filing Surcharge: ₹500 per week\n")
        text_lines.append("SCHEDULE II: Form A (Application Form)")
        text_lines.append("Form of Application for Compliance Certification under Rule 7.")

        raw_text = "\n".join(text_lines)

        documents.append({
            "document_id": doc_id,
            "title": title,
            "document_type": DocumentType.RULES.value,
            "source_authority": SourceAuthority.SYNTHETIC.value,
            "source_name": "LegalLens Synthetic Corpus",
            "source_url": None,
            "synthetic": True,
            "legal_domain": rule_meta["domain"],
            "secondary_domains": [],
            "act_year": rule_meta["year"],
            "act_number": None,
            "jurisdiction": "Union of Bharat (Synthetic)",
            "ministry": rule_meta["ministry"],
            "parent_act_id": rule_meta["parent_act_id"],
            "document_version_group_id": f"vg-{doc_id.lower()}",
            "version_label": "v1.0",
            "publication_date": f"{rule_meta['year']}-04-15",
            "effective_date": f"{rule_meta['year']}-05-01",
            "status": DocumentStatus.ACTIVE.value,
            "section_count": len(rule_items),
            "raw_text": raw_text,
        })

    return documents, all_sections
